FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN rm -rf node_modules package-lock.json \
    && npm i --no-audit --no-fund

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]